# Generated by Django 5.1.3 on 2024-11-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20170625_1450'),
        ('estoque', '0004_alter_localestoque_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamentocompra',
            options={'verbose_name': 'Orçamento de Compra'},
        ),
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'permissions': (('faturar_pedidocompra', 'Pode faturar Pedidos de Compra'),), 'verbose_name': 'Pedido de Compra'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compra_local_estoque', to='estoque.localestoque'),
        ),
        migrations.AlterField(
            model_name='itenscompra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
