version: '3.9'

services:
  # Serviço Web (Django + Gunicorn)
  web:
    build:
      context: .
    volumes:
      - ./erp_mpro/static:/app/erp_mpro/static
      - ./erp_mpro/media:/app/erp_mpro/media
    environment:
      DEBUG: 'False'
      ALLOWED_HOSTS: nformasmoveis.com.br,www.nformasmoveis.com.br
    command: >
      gunicorn --workers 4 --bind 0.0.0.0:8000 erp_mpro.wsgi:application
    restart: always
    expose:
      - "8000"
    networks:
      - erp_network

  # Serviço Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./erp_mpro/static:/app/erp_mpro/static
      - ./erp_mpro/media:/app/erp_mpro/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    networks:
      - erp_network


  # Serviço Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run mpro_erp
    volumes:
      - /etc/cloudflared:/etc/cloudflared
    restart: always
    networks:
      - erp_network

networks:
  erp_network:
    driver: bridge
        