# Generated by Django 5.1.3 on 2024-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20170820_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'verbose_name': 'Lançamento'},
        ),
        migrations.AlterModelOptions(
            name='movimentocaixa',
            options={'permissions': (('acesso_fluxodecaixa', 'Pode acessar o Fluxo de Caixa'),), 'verbose_name': 'Movimento de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='planocontasgrupo',
            options={'verbose_name': 'Grupo do Plano de Contas'},
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimentocaixa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='planocontasgrupo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
