# Generated by Django 5.1.3 on 2024-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_auto_20170915_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaonotafiscal',
            options={'default_permissions': (), 'permissions': (('configurar_nfe', 'Pode modificar configuração de NF-e'),), 'verbose_name': 'Configuração NF-e'},
        ),
        migrations.AlterModelOptions(
            name='grupofiscal',
            options={'verbose_name': 'Grupo Fiscal'},
        ),
        migrations.AlterModelOptions(
            name='naturezaoperacao',
            options={'verbose_name': 'Natureza da Operação'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalentrada',
            options={'verbose_name': 'Nota Fiscal de Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalsaida',
            options={'permissions': (('emitir_notafiscal', 'Pode emitir notas fiscais'), ('cancelar_notafiscal', 'Pode cancelar notas fiscais'), ('gerar_danfe', 'Pode gerar DANFE/DANFCE'), ('consultar_cadastro', 'Pode consultar cadastro no SEFAZ'), ('inutilizar_notafiscal', 'Pode inutilizar notas fiscais'), ('consultar_notafiscal', 'Pode consultar notas fiscais'), ('baixar_notafiscal', 'Pode baixar notas fiscais'), ('manifestacao_destinatario', 'Pode efetuar manifestação do destinatário')), 'verbose_name': 'Nota Fiscal'},
        ),
        migrations.AlterField(
            model_name='autxml',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cofins',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracaonotafiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='errosvalidacaonotafiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupofiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='icms',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='icmssn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='icmsufdest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ipi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='naturezaoperacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respostasefaznotafiscal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
