# Generated by Django 5.1.3 on 2024-11-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_merge_20170625_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localestoque',
            options={'verbose_name': 'Local de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='movimentoestoque',
            options={'permissions': (('consultar_estoque', 'Pode consultar estoque'),), 'verbose_name': 'Movimento de Estoque'},
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_estoque_local', to='estoque.localestoque'),
        ),
        migrations.AlterField(
            model_name='itensmovimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localestoque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produtoestocado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='local_orig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='saida_estoque_local', to='estoque.localestoque'),
        ),
    ]
